#!/bin/bash

# plexilcow (PLEXIL Compiler for OceanWATERS).

# Simple script for compiling a single PLEXIL plan (.plp file).
# Compiled version (.plx) is placed in the current deployment
# directory.  Assumes that the PLEXIL compiler (plexilc) is in the
# user's search path.

if [ $# -ne 1 ]; then
    echo "Usage: $0 <filename.plp>"
    exit 1
fi

input_file="$1"
output_directory="$HOME/ow/devel/.private/ow_plexil/etc/plexil/"

if [ ! -f "${input_file}" ]; then
    echo "Input file '${input_file}' not found."
    exit 1
fi

base_filename=$(basename "$input_file" .plp)

# The '-p' option formats the output XML.

plexilc -p -o "${output_directory}${base_filename}.plx" "${input_file}"
